# Generated by Django 5.2.4 on 2025-09-01 19:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='I',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c', models.CharField(max_length=10)),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
                ('w', models.IntegerField()),
                ('h', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Q',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='IT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rus', models.CharField(max_length=20)),
                ('eng', models.CharField(max_length=20)),
                ('q', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ia', to='pctm.i')),
            ],
        ),
        migrations.CreateModel(
            name='QT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rus', models.CharField(max_length=150)),
                ('eng', models.CharField(max_length=150)),
                ('q', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qu', to='pctm.q')),
            ],
        ),
    ]
