# Generated by Django 5.2.4 on 2025-09-01 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pctm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='q',
            name='eng',
            field=models.CharField(default=0, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='q',
            name='rus',
            field=models.CharField(default=0, max_length=150),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='QT',
        ),
    ]
